version: '3.8'

services:
  josix:
    build: .
    container_name: josix
    restart: always
    environment:
      -
    volumes:
      - ./data/logs:/app/logs
      - ./data/askip.json:/app/askip.json
      - ./data/config.json:/app/config.json
      - ./data/backup.sql:/app/database/backup.sql
      - ./data/daily_backup.sql:/app/database/daily_backup.sql
      - ./data/daily_backup.sql.old:/app/database/daily_backup.sql.old
    depends_on:
      db:
        condition: service_healthy
    networks:
      BridgeServer:
        ipv4_address: 

  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DESIGN: 'hydra'
      ADMINER_DEFAULT_SERVER: 'postgresql'
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      BridgeServer:
        ipv4_address: 

  db:
    image: postgres:latest
    restart: always
    environment:
      -
    volumes:
      - ./initialization-scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U root -d nix'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      BridgeServer:
        ipv4_address: 


networks:
  BridgeServer:
    name: BridgeServer
    driver: 
    driver_opts:
      parent: 
    ipam:
      config:
        - subnet: ""
          gateway: ""